### ISSUE TITLE
Enable github pages

### ISSUE THREAD

**Issue by MottoX** [WING-NUS/SSNLP-2019#2]
Hi Prof.
I cannot open the website [https://WING-NUS.github.io/SSNLP-2019/](https://WING-NUS.github.io/SSNLP-2019/). The reason may be that github pages is not enabled. Could you enable by going to Insights->Options and making the website built from the master branch? And we can further update the description and website link of this repository. Currently, I don't have github permission to do these things.

**Comment by knmnyn** [comment]
Done.  Please note that although the github.io pages are now active you need to mount the actual static webpages on a directory in the wing-nus.comp.nus.edu.sg VM and have a symlink to the pages wherever they are in the htdocs (if not actually in the htdocs root)

**Comment by MottoX** [comment]
Hi Prof. @knmnyn 
Maybe I misunderstood something previously. I meant to just use **WING-NUS.github.io** as the domain name of our website because many other conference websites also just leverage github's github.io pages. Are you meaning that we use **wing.comp.nus.edu.sg** as the domain name? Can you tell me who is familiar with this and know how to config it, so that I can do it faster?

**Comment by knmnyn** [comment]
Hi Weixin:

Wenqiang and Yisong I believe can help with the wing-nus.comp VM
configuration, also @Kishaloy.

You need to create a symlink to a directory in the VM from the htdocs
directory (usually something like /etc/apache2/htdocs and put the directory
of static webpages to serve from there.  Hope that helps!

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
